version: "3.7"
services:
  db:
    image: postgres:13.0
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - backnet
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  cache:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${CACHE_PASSWORD}
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - backnet
    environment:
      - REDIS_REPLICATION_MODE=master
  app:
    build: app
    restart: always
    volumes:
      - ./app:/code
    ports:
      - 5678:5678
    networks:
      - backnet
      - frontnet
    depends_on:
      - db
      - cache
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
      - CACHE_PASSWORD=${CACHE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
  web:
    build: web
    restart: always
    ports:
      - 80:80
    networks:
      - frontnet
    depends_on:
      - app
volumes:
  db-data:
  redis-data:
  redis.conf:
networks:
  backnet:
  frontnet:
