version: "3.7"
services:
  db:
    image: postgres:13.0
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - backnet
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=wishlist
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  app:
    build: app
    restart: always
    volumes:
      - ./app:/code
    ports:
      - 5678:5678
    networks:
      - backnet
      - frontnet
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
  web:
    build: web
    restart: always
    ports:
      - 80:80
    networks:
      - frontnet
    depends_on:
      - app
volumes:
  db-data:
networks:
  backnet:
  frontnet:
